name: Build Code

on: [push, pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.43
        args: --timeout=5m0s

    - name: Vet
      run: make vet

  test:
    needs: linters
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Run unit tests
      run: make tests

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build
      run: make build